# lobby: 常時稼働。void ワールド（中央に石の足場）でアドベンチャーモード
server-port=30001
server-ip=127.0.0.1
online-mode=false
enable-command-block=false
view-distance=10
simulation-distance=10
motd=lobby
gamemode=adventure
force-gamemode=true
difficulty=peaceful
pvp=false
spawn-monsters=false
spawn-animals=false
generate-structures=false
allow-nether=false
spawn-protection=64
level-type=minecraft\:flat
generator-settings={"layers":[{"block":"minecraft:air","height":1}],"biome":"minecraft:the_void","features":true,"lakes":false,"structure_overrides":[]}
