# s1: 通常サバイバル。無人になると自動停止
server-port=30002
server-ip=127.0.0.1
online-mode=false
enable-command-block=false
view-distance=10
simulation-distance=10
motd=s1
gamemode=survival
difficulty=normal
pvp=true
spawn-protection=0
