# dev: 管理者用の開発鯖。/dev（管理者のみ）か /network start dev で起動
server-port=30004
server-ip=127.0.0.1
online-mode=false
enable-command-block=false
view-distance=10
simulation-distance=10
motd=dev
gamemode=creative
difficulty=normal
spawn-protection=0
